version: '3.8'

services:
  pd-anonymizer:
    build: .
    container_name: pd-anonymizer
    restart: always
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp
      - /home/deploy/.cache:uid=1000,gid=1000
    ports:
      - "8005:8000"
    volumes:
      - ./api_keys.json:/app/api_keys.json
    environment:
      - LOG_LEVEL=INFO
      # API_KEY больше не используется, так как ключи вынесены в JSON
      # - API_KEY=...
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')\""]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
